### ISSUE TITLE
Accessibility: 'Buttons do not have an accessible name'

### ISSUE THREAD

**Issue by VallyPepyako** [jkhaui/react-glidejs#4]
Lighthouse accessibility audit message 'Buttons do not have an accessible name'. Here are the two element listed:
`<button data-glide-dir="<" class="_10XKC Glide-leftArrow"></button> `
` <button data-glide-dir=">" class="_10XKC Glide-rightArrow"></button>`

**Comment by jkhaui** [comment]
Hey @VallyPepyako sorry for the late reply. Thanks for raising this issue. I'll be doing a refactor within a couple of weeks and will make sure to rectify this.
